blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/yosasasutsut/GameLANVPN/discussions
    about: Suggest new features or improvements
  - name: ğŸ› Bug Report
    url: https://github.com/yosasasutsut/GameLANVPN/issues/new
    about: Report bugs or issues
  - name: ğŸ“š Documentation
    url: https://github.com/yosasasutsut/GameLANVPN/wiki
    about: Check documentation and guides